version: "3"
services:
  postgres:
    build: './db'
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "barucija"
      POSTGRES_HOST_AUTH_METHOD: password
    restart: unless-stopped
  spring-boot-app:
    image: haremetak94/spring-boot-app
    container_name: spring-boot-app
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
      - node
    links:
      - postgres
      - node
  node:
    image: haremetak94/docker-node-app
    container_name: docker-node-app
    expose:
      - 8081
    ports:
      - 8081:8081